name: Test SARIF

on:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: result.sarif
          category: mutation-testing
      - name:
        run: |
          echo "##[warning]main.c:6:5: warning: survived cxx_add_to_sub"

