name: Test SARIF

on:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: result.sarif
          category: mutation-testing
          wait-for-processing: true
      - name:
        run: |
          echo $PWD
          text="survived cxx_add_to_sub"
          echo "::warning file=/home/runner/work/test-sarif/test-sarif/main.c,line=6,col=5::$text"

